### ISSUE TITLE
Uses AWS V1 and eb_deployer now uses V2

### ISSUE THREAD

**Issue by aterreno** [alienfast/elastic-beanstalk#19]
It seems like the gem is trying to use AWS gem v1 (uppercase AWS) while eb_deployer has a dependency over AWS gem v2 (lowercase AWS) 

λ ~/code/ master* rake eb:package eb:deploy                                                                          
rm -r pkg
rake aborted!
NameError: uninitialized constant AWS
/home/toni/.rvm/gems/ruby-2.2.1/gems/elastic-beanstalk-1.1.3/lib/elastic/beanstalk/tasks/eb.rake:184:in `block (2 levels) in <top (required)>'
-e:1:in `<main>'
Tasks: TOP => eb:package => eb:config
(See full trace by running task with --trace)

**Comment by rosskevin** [comment]
The gem replies upon eb_deployer solely for the deployment portion, it must be the convenience RDS tasks that are `require`ing the V1 gem in `eb.rake`.   You probably experienced it because you did a recent bundle install and eb_deployer migrated.   Note this gem expects to get it from the transitive dependency from eb_deployer and doesn't specify it.

It should be an easy fix if you want to take a shot and submit a pull.  Just try running an RDS task and fix `eb.rake`.  Otherwise I'll try to take a look later today.

**Comment by rosskevin** [comment]
Merged and deployed 1.1.4.  Can you give that a shot and close if all is well?

Thank you
