### ISSUE TITLE
Running Background Jobs - Worker Tier & SQS or Sidekiq/Suckerpunch/Reque/DelayedJob?

### ISSUE THREAD

**Issue by dashbitla** [alienfast/elastic-beanstalk#35]
Whats the best way to run the Background Jobs? 
Should we go for 
Worker Tier & SQS or 
Sidekiq/Suckerpunch/Reque/DelayedJob?

Also, when we deploy using eb:deploy, we need to set tier to WorkerTier and deploy is it? OR can the eb deploy for both Web & Worker tiers are the same time, if so any such example configuration? 

What settings are there for configuring worker tier? 
Thank you much in advance.

**Comment by rosskevin** [comment]
I haven't deployed a worker tier yet but our scalability is planned around sidekiq pro with elasticache(redis).  I plan to do some testing around what is the best for a worker tier, and we are considering alternatives such as EB for web only with docker containers for workers.  But nonetheless, I've not deployed and tested that scenario, only done enough to implement sidekiq/redis in development/testing.

In my experience, sidekiq is great and sidekiq pro gets you the bulletproof features.  The simple offloading of work to sidekiq/redis can add dramatic scale to this sort of architecture and reduce necessary running instances.  There is a SEDA (synchronous event driven architecture) paper out there somewhere that is really applicable to this approach.  See http://www.eecs.harvard.edu/~mdw/proj/seda/

I've done some good work with rails/docker here:  https://github.com/alienfast/docker-rails

I'm really interested in containers, and in essence you could view EB as a container with more orchestration.  I think eventually EB could get phased out with containers taking over, but it will take a while before the orchestration meets the level that EB provides.  I do however think that containers _might_ be where they need to be in order to run the worker tier...definitely worth looking at.

**Comment by dashbitla** [comment]
We currently use Sidekiq with non aws infrastructure on a separate server. We are moving to AWS.

How can we configure the EB environment a dedicated instance for Sidekiq where no other web requests are processed by this instance? Leader only flag also will not help as such, as it's part of web tier. Under load Sidekiq stops as it fights for resources when web requests are keeping the instance busy. 

Any sample configuration for Worker tier?

I will try docker rails for next phase of our infra rollout.

**Comment by rosskevin** [comment]
See

http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features-managing-env-tiers.html

And

https://github.com/ThoughtWorksStudios/eb_deployer/issues/34#issuecomment-76432311
