### ISSUE TITLE
custom CNAME? what am I missing?

### ISSUE THREAD

**Issue by mepatterson** [alienfast/elastic-beanstalk#36]
I have a relatively generic app name... let's say it's called "myapp". So when I try to create a "staging" environment, the deploy tells EB it wants "myapp-staging.elasticbeanstalk.com" which then throws

```
Aws::ElasticBeanstalk::Errors::InvalidParameterValue: DNS name (myapp-staging.elasticbeanstalk.com) is not available.
```

and crashes the whole deploy.

I don't want to have to rename my entire app something crazy just because someone else out there has that same subdomain. (I'm going to point my own domain name at it via Route53 anyway)

What am I missing here? I can't find any examples between this project and eb_deployer showing how to ensure I get an available DNS name. I tried using `cname_prefix` to prefix the DNS name with something that will probably be unique, but the deploy seemed to ignore that and gave me the same error as above. Is there some setting I need to set to achieve this?

**Comment by rosskevin** [comment]
I have route53 setup that routes to my elastic loadbalancer which is auto-created upon deploy.  It's pretty easy to deploy without the cname, then go to the aws console and configure the cname to point to the active loadbalancer (it will give you a dropdown list).

I don't do this automatically, but it is not often that I destroy the entire environment and need to reset it.  It would be nice to configure this automatically but I haven't taken the time to figure it out.

Please let me know what you figure out.

**Comment by mepatterson** [comment]
So I've dug deeper and found a couple things, but other things I'm still confused about:

1. `eb.rake` around line 330 or so, we're not explicitly passing `options[:cname_prefix]` along to eb_deployer, which is why that's not working. I hacked it in on my local system and it worked and created an EB environment with the cname I wanted. However, I don't know what this is going to do in a blue-green situation... I don't fully grok all of eb_deployer's code yet.

2. I dug into eb_deployer's code and it seems like the process there is to ask EB what the environment is after it has created it on the AWS side, so it gets back something like "staging-6cd3d07" which, when prefixed with "myapp-" and combined with ".elasticbeanstalk.com" should always be unique. But the elastic-beanstalk gem is explicitly telling it to use "myapp-staging" with no hash on the end, which someone else out there is already using, so I guess eb_deployer passes that along to its `create_environment` method and then EB gives up and dies.

not sure how to go about getting the desired behavior, though. Basically, what I want to do is:

`rake eb:package[staging] eb:deploy[staging]`

and have it create my application and environment on EB and deploy my latest code. The cname should be something like "myapp-staging-6cd3d07". Then I can go over to route53 and associate it with my own domain, or put an ELB in front of it, or whatever...

I'm not sure I follow what you mean by "...easy to deploy without the cname..." though? It seems like this gem is always going to force eb_deployer to try and create an environment with a specific cname that might not be available, right? Or am I totally confused about something?

**Comment by rosskevin** [comment]
1.  Additional options could be passed if you want, just PR that.
2.  If I recall correctly, eb_deployer will create the cname from the environment and `app` name.

The app environment I have deployed is `staging-c61fe25` but cnamed something like `acme-staging.elasticbeanstalk.com`

I guess I've never had a cname conflict because I use our TLD domain name as our app name, therefore it's unlikely for someone to be using that.

The issue here is with eb_deployer (I'm not saying it's a bug with them), I would check their docs about customizing the deployed name.  Perhaps you are on the right track with just passing that `cname_prefix` option, in that case just PR a change to this section: https://github.com/alienfast/elastic-beanstalk/blob/master/lib/elastic/beanstalk/tasks/eb.rake#L328 
and this section: https://github.com/alienfast/elastic-beanstalk/blob/master/README.md#eb_deployer-additional-options

**Comment by mepatterson** [comment]
we can close this. it's pretty clear what the issue was. calling your app something more unique "myappname-mydomain" fixes this in 99% of cases, I suspect, as you noted.
