### ISSUE TITLE
Override EB Environment Name

### ISSUE THREAD

**Issue by kotowick** [alienfast/elastic-beanstalk#50]
By default, it seems that the environment name has a uniq hash appended to it from eb_deployer. Could this be set as an option? In some cases, it would be ideal for the EB ENV name to match the branch name (for example).

Also, not sure what I am doing wrong, but running "eb:package[development]" returns: no matches found: eb:package[development].

**Comment by rosskevin** [comment]
I'm not sure about the environment hash as we are not actively using this anymore.

Regarding the command, if you don't have a `development` in your yaml, I suppose that is one possibility.  Since I can't see your config, the stack trace, your gemfile etc it's hard to diagnose with the information provided.

Ultimately, there isn't much in this project, just a thin rake task wrapper over eb deployer so it should be pretty easy to step through with a debugger.

**Comment by kotowick** [comment]
Thanks  @rosskevin. I solved the latter issue. I ended up on forking the project and made a small modification to the eb env naming convention. I will close this.
